# Generated by Django 4.1.7 on 2023-03-20 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0003_alter_activity_related_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activities.activity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activities.country')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='countries',
            field=models.ManyToManyField(through='Activities.Vacation', to='Activities.country'),
        ),
        migrations.AddField(
            model_name='country',
            name='activities',
            field=models.ManyToManyField(through='Activities.Vacation', to='Activities.activity'),
        ),
    ]
