# Generated by Django 4.1.7 on 2023-03-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0004_vacation_activity_countries_country_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='money_required',
            field=models.IntegerField(),
        ),
    ]
