# Generated by Django 4.1.7 on 2023-03-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0005_alter_activity_money_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='date',
        ),
        migrations.AddField(
            model_name='vacation',
            name='month',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
