# Generated by Django 4.1.7 on 2023-03-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0006_remove_vacation_date_vacation_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='related_season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Activities.season'),
            preserve_default=False,
        ),
    ]
