# Generated by Django 4.1.7 on 2023-03-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('related_season', models.CharField(max_length=100)),
                ('a_person_to_complete_the_activity_with', models.CharField(max_length=100)),
                ('money_required', models.CharField(max_length=100)),
                ('time_required', models.CharField(max_length=100)),
            ],
        ),
    ]
