# Generated by Django 4.1.7 on 2023-03-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0002_alter_country_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='related_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Activities.season'),
        ),
    ]
